version: '3'
name: 'prestashop'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: some-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: admin
    restart: always
    ports:
      - "9090:80"
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:8.1.3
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
      PS_FOLDER_ADMIN: admina
    networks:
      - prestashop_network
networks:
    prestashop_network: